### PR TITLE
fix(ObjectPage): Prevent infinite grow

### LINKED ISSUE #373: ObjectPage: Reducing the screen size makes the ObjectSection grow
**Describe the bug**
Reducing the size of the Browser view port make the ObjectSection margin-bottom grow infinitely.

**To Reproduce**
1. Reduce the size of your browser window
2. You should see the ObjectSection expanding itself to the bottom

**Expected behavior**
The ObjectSection should only grow on resize to properly display its child elements.

**GIFs**
objectpage1
NB: I changed the background color of the ObjectSection to better illustrate the "growing effect". When reducing the window size, we can see the ObjectSection expanding to the bottom.
The Scrollbar also reflects this.

objectpage2
Reducing the size of the window with the debugger tools opened shows the `margin-bottom` increasing.

**UI5 Web Components for React Information**
Operating System: macOS
`@ui5/webcomponents-react` version: 0.9.0-rc.2
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.5

### PR DESCRIPTION
**Pull request by MarcusNotheis**
Limiting the ObjectPage Margin Bottom to the window height.

Closes #373

### CODE REVIEW

File: packages/main/src/components/ObjectPage/index.tsx [hunk 1]
```diff
@@ -243,7 +243,11 @@ const ObjectPage: FC<ObjectPagePropTypes> = forwardRef((props: ObjectPagePropTyp
 
   useEffect(() => {
     const fillerDivObserver = new ResizeObserver(() => {
-      const availableScrollHeight = objectPageRef.current.clientHeight - totalHeaderHeight;
+      const maxHeight =
+        objectPageRef.current.clientHeight > window.innerHeight
```
Comment (vbersch) [inline packages/main/src/components/ObjectPage/index.tsx]: `Math.min(objectPageRef.current.clientHeight, window.innerHeight)` ?

Comment (MarcusNotheis) [reply packages/main/src/components/ObjectPage/index.tsx]: good point :)
