### PR TITLE
fix(AnalyticalTable): calculate scrollbar width only if table is scrollable

### LINKED ISSUE #467: Analytical Table: The width for scrollbar still remains in analytical table
**Describe the bug**
While using an analytical table, if data is enough to show the scrollbar, everything goes well, however, while there are only a few data and scrollbar doesn't appear, the width still remains.

**To Reproduce**
1. Create a component with analytical table with only a few data.

**Expected behavior**
The width for scrollbar should disappear while there is no scrollbar

**Screenshots**
This image shows the bug.
Screen Shot 2020-04-30 at 11 08 34 AM

This image works good.
Screen Shot 2020-04-30 at 11 08 12 AM

**UI5 Web Components for React Information**
Operating System:
"@ui5/webcomponents": "1.0.0-rc.6",
"@ui5/webcomponents-fiori": "1.0.0-rc.6",
"@ui5/webcomponents-icons": "1.0.0-rc.6",
"@ui5/webcomponents-react": "^0.9.0-rc.14",

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

### PR DESCRIPTION
**Pull request by MarcusNotheis**
Fixes #467

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/index.tsx [hunk 1]
```diff
@@ -252,6 +252,12 @@ const AnalyticalTable: FC<TableProps> = forwardRef((props: TableProps, ref: Ref<
     useRTL
   );
 
+  // scroll bar detection
+  useEffect(() => {
+    const visibleRowCount = rows.length < visibleRows ? Math.max(rows.length, minRows) : visibleRows;
+    dispatch({ type: 'TABLE_SCROLLING_ENABLED', payload: { isScrollable: data.length > visibleRowCount } });
+  }, [rows.length, minRows, visibleRows]);
```
Comment (Lukas742) [inline packages/main/src/components/AnalyticalTable/index.tsx:259]: Add `data.length` to dependencies array
```suggestion
  }, [rows.length, minRows, visibleRows, data.length]);
```

Comment (MarcusNotheis) [reply packages/main/src/components/AnalyticalTable/index.tsx:259]: changed it to use rows.length - otherwise filtering would not be respected
