### PR TITLE
fix(AnalyticalTable): improve accessibility

### LINKED ISSUE #5819: AnalyticalTable - ACC: Table header read twice
### Describe the bug

On accessing the table rows header items are read twice.

Affected Component
AnalyticalTable

### Isolated Example

https://stackblitz.com/edit/github-wv3ad2-gzokbg?file=src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

The table header should be read once.

Screenshot :

image

### Screenshots or Videos

_No response_

### UI5 Web Components for React Version

18.3.1

### UI5 Web Components Version

1.120.4

### Browser

Chrome

### Operating System

Microsoft Windows 11 x64

### Additional Context

Screen Reader: JAWS 2023.2307.37 ILM 64bit for Windows

### Relevant log output

_No response_

### Priority

Medium

### Organization

CBC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### LINKED ISSUE #7387: AnalyticalTable: A11Y - Repetitive column name announcements for screenreaders on navigating cells across columns
### Describe the bug

On navigating data cells in the Analytical Table in a horizontal direction across columns, the column name is announced twice by screenreaders. Video of the issue with sound is added as an example. Tested using JAWS 2025.

### Isolated Example

https://stackblitz.com/edit/ui5wcr-at-kzftabqt?file=src%2FApp.tsx

### Reproduction steps

1. Go to the linked stackblitz
2. Start JAWS or any other screenreader tool
3. Navigate across cells horizontally
4. Repetitive announcements for the column names are made

### Expected Behaviour

No repetitive announcements by screenreaders

### Screenshots or Videos

https://github.com/user-attachments/assets/d28e5ac4-a902-471c-8daf-209c120eb1fe

### UI5 Web Components for React Version

2.10.0

### UI5 Web Components Version

2.10.0

### Browser

Edge

### Operating System

_No response_

### Additional Context

_No response_

### Relevant log output

```shell

```

### Organization

SAP

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by Lukas742**
Fixes #7387
Fixes #5819

On entry:
- “[Table title] grid” (Table title if set, “Grid” by screen reader reading the role)
  - `data-component-name="AnalyticalTableContainer"`: role=grid, aria-labelledby --> `header` prop
- Total row/col count: “Table contains 123 rows and 14 columns ”
  - `data-component-name="AnalyticalTableContainer"`: aria-rowcount, aria-colcount

Column headers navigation:
- “Header” plus header cell text
  - role=columnheader, text (if not text content, can be defined via `headerLabel`)
- Header cells may contain actions like sort. This should be also announced.
  - aria-expanded, aria-controls, aria-haspopup, for column header popover
  - Selection, Highlight & Navigation column header announcement
- Sort/Filter Status of row/columns must be indicated
  - sort: aria-sort
  - filter: aria-label="Filtered"
  - group: aria-label="Grouped"
- Header Hierarchies (level 1, 2 ..) must be announced
  - N.A.

Row/Cell navigation:
- Grid Cell Row/Col info = header text + position while arrowing through grid
  - Header: 
    - JAWS/NVDA: relation is made via roles (`columnheader` -> `gridcell`) to prevent duplicate announcements (following wcag2.2 specs)
    - VoiceOver: `aria-labelledby` pointing to column header id (workaround)
  - position: `aria-colindex`
- For tables with n rows, speech output should always be <row nr of n rows>, no matter how many rows are visible. If n is not known, speech output should always be <row nr>
  - `aria-rowindex` -> is ignored by VoiceOver - NVDA reads it, if this becomes an issue use live announcement via invisible messaging
- Focused cells: Role and label of cell content
  - `aria-labelledby`
  - Interactive content: native in F5 hook, otherwise has to be defined via `cellLabel` prop
- Selection state of cell/row must be announced
  - `aria-selected` + live announcement when state changes
- Group Header Rows in Table must be announced as such
  - "Grouped" is announced when focusing cell in group header row
- Freezing state of s column must be announced
  - N.A.

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx [hunk 1]
```diff
@@ -174,10 +174,11 @@ export const ColumnHeaderModal = (instance: TableInstanceWithPopoverProps) => {
         ref.current.open = true;
       });
     }
-  }, []);
+  }, [openerRef]);
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/defaults/Column/ColumnHeaderModal.tsx]: is openerRef even changing? Shouldn't refs be avoided in dependency arrays?

**Review by MarcusNotheis — APPROVED** [review]
