### PR TITLE
fix(VariantManagement): call onSaveManageViews only with callbackProperties

### LINKED ISSUE #2714: VariantManagement: Calling callback too early
**Describe the bug**
Callback is being called and then parameter of the callback function is updated/mutates.

**Expected behavior**
Only call the callback once its parameter has its properties set and do not mutate it after the call.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.2.1
`@ui5/webcomponents-react` version: 0.22.2
Operating System: MAC
Browser: Chrome

**Additional context**
[Pull request](https://github.com/SAP/ui5-webcomponents-react/pull/2701)

### PR DESCRIPTION
**Pull request by guedes4g**
This Pr fixes VariantManagement onSaveManageViews being called with empty callback properties

Fixes #2714

### CODE REVIEW

File: packages/main/src/components/VariantManagement/index.tsx [hunk 1]
```diff
@@ -353,6 +350,9 @@ const VariantManagement = forwardRef((props: VariantManagementPropTypes, ref: Re
             });
           }
           callbackProperties.variants.push({ ...child.props, ...updatedProps, variantItem: currentVariant });
+          if (typeof onSaveManageViews === 'function') {
+            onSaveManageViews(enrichEventWithDetails(e, callbackProperties));
+          }
```
Comment (Lukas742) [inline packages/main/src/components/VariantManagement/index.tsx:355]: Please call the function outside of the `map` and setter.

**Review by Lukas742 — CHANGES_REQUESTED** [review]

File: packages/main/src/components/VariantManagement/index.tsx (hunk 1 above)
Comment (guedes4g) [reply packages/main/src/components/VariantManagement/index.tsx]: Moved

**Review by Lukas742 — APPROVED** [review]
LGTM! Thanks for your contribution :)
