### PR TITLE
fix(AnalyticalTable): support horizon theme

### LINKED ISSUE #3175: AnalyticalTable: Contrast ratio of Table Borders do not match in default and HCB theme
**Describe the bug**
AnalyticalTable - contrast ratio of table borders do not match in default and HCB theme.

**UI Link**
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--default-story

**Expected behavior**

**Screenshots**
image

image

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.6
Operating System: Windows 11
Browser: Chrome

### PR DESCRIPTION
**Pull request by MarcusNotheis**
- updated Table Headers to use bold font family
- updated table header border color
- updated grouped cells (bold font)

Fixes #3175

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx [hunk 1]
```diff
@@ -52,10 +47,7 @@ export const VerticalScrollbar = forwardRef((props: VerticalScrollbarProps, ref:
   const classes = useStyles();
   const hasHorizontalScrollbar = tableRef?.current?.offsetWidth !== tableRef?.current?.scrollWidth;
 
-  const horizontalScrollbarSectionStyles = clsx(
-    classes.bottomSection,
-    hasHorizontalScrollbar && classes.bottomSectionWithScrollbar
-  );
+  const horizontalScrollbarSectionStyles = clsx(hasHorizontalScrollbar && classes.bottomSection);
 
   return (
```
Comment (Lukas742) [inline packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx:52]: I couldn't mark the correct line, as there are no changes, but could you set the `width: '1px'` in line 77 to `'0.1px'`. This will prevent the border from looking bold. (especially with dark themes)

image

**Review by Lukas742 — CHANGES_REQUESTED** [review]
- With rtl direction the header cells are not aligned to the body cells:
image

**Review by Lukas742 — APPROVED** [review]
