### PR TITLE
fix(AnalyticalTable): return correct values in `onRowSelect` callback

### LINKED ISSUE #3612: [SAP][Analytical Table] onSelectionChange gives wrong data
!! It is needed for Internal SAP consumption !!

image

**Describe the bug**
onSelectionChange event has property selectedFlatRows

on checking for a parent node which has some unselected items
**isSomeSelected is coming as false.**

Expected behavior
**it should be true.**

UI5 Web Components for React Information
@ui5/webcomponents-react version: v 1.0.1
Operating System: macos
Browser: chrome

It is needed for Internal SAP consumption

### LINKED ISSUE #3659: [SAP][Analytical Table][HIGH] SelectedFlatRows only contains only those selected rows which are visible in ui
**Describe the bug**
SelectedFlatRows only contains only those selected rows which are visible in UI

**To Reproduce**
1) Filter a row and select it.
2) filter another row (previously selected row should not be visible)

Observation
e.detail.selectedFaltRows only has 1 item in array (the selected row which got filtered is not part of array)
3) remove the filter
Observation
selected rows which got filtered are still selected.

**Expected behavior**
all the selected rows should be returned as flat rows

https://user-images.githubusercontent.com/57886348/196667474-fc7ac495-ce55-465f-ba4e-705b74fe4088.mov

UI5 Web Components for React Information
@ui5/webcomponents-react version: v 1.0.1
Operating System: macos
Browser: chrome

It is needed for Internal SAP consumption

### PR DESCRIPTION
**Pull request by Lukas742**
Fixes #3659 
Fixes #3612

### CODE REVIEW

**Review by MarcusNotheis — APPROVED** [review]

File: packages/main/src/components/AnalyticalTable/hooks/useSelectionChangeCallback.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+  hooks.useControlledState.push((state, { instance }) => {
+    const { selectedRowPayload, selectedRowIds } = state;
+    const { rowsById, webComponentsReactProperties, selectedFlatRows } = instance;
+    useEffect(() => {
+      if (selectedRowPayload) {
+        const { event: e, row: selRow } = selectedRowPayload;
+        const row = rowsById[selRow.id];
+        const payload = {
+          row: row,
+          isSelected: row.isSelected,
```
Comment (thisisjasmeet) [inline packages/main/src/components/AnalyticalTable/hooks/useSelectionChangeCallback.ts:15]: this change is causing a regression issue 

https://user-images.githubusercontent.com/57886348/197931563-b904dc8f-7cbe-4cb4-a4f9-56735d0b4780.mp4

**Comment by thisisjasmeet** [comment]
@Lukas742  this fix is causing a regression


https://user-images.githubusercontent.com/57886348/197931664-e9fa1737-f8bd-45d0-a8bc-b6415df063b5.mp4
