### PR TITLE
fix(DynamicPageTitle): reduce title font-size for small devices

### LINKED ISSUE #2939: [SF][0.23.0][DynamicPage] Page title's font size does not reduce when page size reduced
Please see wiki page for reference(will provide link separately) , the page title's font size should reduce when page narrow down to small size.

### PR DESCRIPTION
**Pull request by Lukas742**
This PR reduces the font-size of the title when displayed on phone.

Fixes #2939

### CODE REVIEW

File: packages/main/src/components/DynamicPageTitle/index.tsx [hunk 1]
```diff
@@ -125,11 +125,19 @@ const DynamicPageTitle = forwardRef((props: DynamicPageTitlePropTypes, ref: Ref<
   } = props as InternalProps;
 
   const classes = useStyles();
-  const containerClasses = clsx(classes.container, className, Device.isIE() && classes.iEClass);
   const [componentRef, dynamicPageTitleRef] = useSyncRef<HTMLDivElement>(ref);
   const [showNavigationInTopArea, setShowNavigationInTopArea] = useState(undefined);
   const isRtl = useIsRTL(dynamicPageTitleRef);
   const isMounted = useRef(false);
+  const [isPhone, setIsPhone] = useState(
+    Device.getCurrentRange(dynamicPageTitleRef.current?.getBoundingClientRect().width).name === 'Phone'
```
Comment (MarcusNotheis) [inline packages/main/src/components/DynamicPageTitle/index.tsx:133]:
```suggestion
    Device.getCurrentRange(dynamicPageTitleRef.current?.getBoundingClientRect().width)?.name === 'Phone'
```
Do we need optional chaining here?

File: packages/main/src/components/DynamicPageTitle/index.tsx [hunk 2]
```diff
@@ -163,6 +171,7 @@ const DynamicPageTitle = forwardRef((props: DynamicPageTitlePropTypes, ref: Ref<
         : titleContainer.borderBoxSize;
       // Safari doesn't implement `borderBoxSize`
       const titleContainerWidth = borderBoxSize?.inlineSize ?? titleContainer.target.getBoundingClientRect().width;
+      setIsPhone(Device.getCurrentRange(titleContainerWidth).name === 'Phone');
```
Comment (MarcusNotheis) [inline packages/main/src/components/DynamicPageTitle/index.tsx:174]:
```suggestion
      setIsPhone(Device.getCurrentRange(titleContainerWidth)?.name === 'Phone');
```
Do we need optional chaining here?

**Review by MarcusNotheis — CHANGES_REQUESTED** [review]

File: packages/main/src/components/DynamicPageTitle/index.tsx (hunk 1 above)
Comment (Lukas742) [reply packages/main/src/components/DynamicPageTitle/index.tsx:133]: I thought we don't, because if the parameter of `getCurrentRange` is undefined, it should fall back to the window width, but since we use optional chaining in the other implementations, I think it's saver to add it here as well. (Maybe there where issues with the implementation if the `window` wasn't defined)

**Review by MarcusNotheis — APPROVED** [review]
