### PR TITLE
fix(AnalyticalTable): fix vertical scrollbar styles and sync logic

### LINKED ISSUE #7831: [AnalyticalTable]: [Scroll doesn't change position]
### Describe the bug

Hi, 

Hi, I noticed a bug in version 2.15.* with AnalyticalTable component. When I added `visibleRowCountMode="AutoWithEmptyRows"`  the scroll position doesn't change when scrolling with the mouse.

IMPORTANT: 
Scroll doesn't work correctly only when version **Vite** is higher than 6..0. 

Regards
Krzysztof

### Isolated Example

https://stackblitz.com/edit/ui5wcr-at-xezyfxpy?file=src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

_No response_

### Screenshots or Videos

_No response_

### UI5 Web Components for React Version

2.15.*

### UI5 Web Components Version

2.15.*

### Browser

Chrome

### Operating System

_No response_

### Additional Context

_No response_

### Relevant log output

```shell

```

### Organization

_No response_

### Declaration

- [x] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by Lukas742**
All of these issues are caused, because of the new global `scrollbar-color` CSS property.

__Chrome:__ 
- scrollbar track height is not updated correctly in some cases
image

_Here the table is scrolled to the last row_

__Solution:__ force reflow to update scrollbar track height

__Firefox:__
- scrollbar container do not automatically adjust to the scrollbar width, leading to hidden scrollbars if no `width` is set.
- scrollbars do not scale in Firefox -> scrollbar container width would have to be calculated according to scale value.

__Solution:__ Use native scrollbar and add padding in last cells to prevent content from being hidden

__General:__
- Improve scroll performance when dragging scrollbar
- Fix issue with scroll synchronization when updating `data`

___

Fixes #7831

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/index.tsx [hunk 1]
```diff
@@ -99,6 +100,8 @@ import {
 } from './util/index.js';
 import { VerticalResizer } from './VerticalResizer.js';
 
+const isFirefox = isFireFoxFn();
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/index.tsx]: Could lead to an hydration error in SSR environments. This returns always false on the server, on some clients it might be true -> Hydration Error

File: packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx [hunk 2]
```diff
@@ -13,10 +15,35 @@ interface VerticalScrollbarProps {
   classNames: ClassNames;
 }
 
+const isChrome = isChromeFn();
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/scrollbars/VerticalScrollbar.tsx]: Could lead to an hydration error in SSR environments. This returns always false on the server, on some clients it might be true -> Hydration Error

**Review by MarcusNotheis — APPROVED** [review]
