### PR TITLE
fix(SplitterLayout): correct margin & grip button styles

### LINKED ISSUE #3403: SplitterLayout: unnecessary margin on Splitter element
**Describe the bug**
The draggable Splitter is rendered with an unnecessary horizontal margin, making it impossible to fully collapse a section.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/main/?path=/docs/layouts-floorplans-splitterlayout--nested

image

**To Reproduce**
1. Go to the [storybook](https://sap.github.io/ui5-webcomponents-react/main/?path=/docs/layouts-floorplans-splitterlayout--nested)
2. See that each Splitter has a left and right margin

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: main

### PR DESCRIPTION
**Pull request by EtienneWille**
fixes #3403

### CODE REVIEW

File: packages/main/src/components/Splitter/index.tsx [hunk 1]
```diff
@@ -126,7 +124,13 @@ const useStyles = createUseStyles(
       minWidth: '1.5rem !important',
       height: '1.625rem',
       backgroundColor: `${ThemingParameters.sapShell_Background}`,
-      zIndex: '1'
+      zIndex: '1',
+      '&:active': {
+        zIndex: '2'
+      },
+      '&:hover': {
+        backgroundColor: CustomThemingParameters.SplitterGripHoverColor
```
Comment (Lukas742) [inline packages/main/src/components/Splitter/index.tsx:132]: Please remove all custom color styles (also the one in line 126) from the `gripButton` and use the default design of the transparent button instead. You can achieve that by adding `design={ButtonDesign.Transparent}` to the `Button` component

**Review by Lukas742 — CHANGES_REQUESTED** [review]

**Review by Lukas742 — APPROVED** [review]
