### PR TITLE
fix(AnalyticalTable): always scale cols correctly with `scaleWidthMode` "Grow"

### LINKED ISSUE #4348: AnalyticalTable: Sets column sizes in a strange way
### Describe the bug

There's a strange behaviour with the AnalyticalTable with `scaleWidthMode` set to `Grow` that is grouped by default and two columns with fixed size. As you can see in my screenshots, that table won't fit completly in my parent container. When I remove my fixed sizes, then the table will fit into the container.

I tried to attach a codesandbox example, but the template seems broken, so I'm not able to provide code.

### Isolated Example

_No response_

### Reproduction steps

1. Build an `AnalyticalTable`
2. Build up to 8 Columns
3. Give 2 columns a width of 110px and 80px
4. Fill table with data and set `scaleWidthMode` to `Grow`
5. Set the `groupBy` property to group the table by default

### Expected Behaviour

I expect, that the table columns will fit in their parent container

### Screenshots or Videos

image
image

### UI5 Web Components for React Version

1.11.3

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

Windows

### Additional Context

_No response_

### Relevant log output

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by Lukas742**
Fixes #4348

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/index.tsx [hunk 1]
```diff
@@ -418,7 +418,7 @@ export interface AnalyticalTablePropTypes extends Omit<CommonProps, 'title'> {
...
-   * - **Grow**: Every column gets the space it needs for displaying its full header text and full text content of all cells. If it requires more space than the table has, horizontal scrolling will be enabled. To prevent huge header text from polluting the table, a max-width of 700px is applied to each column. It can be overwritten by setting the respective column property.
+   * - **Grow**: Every column gets the space it needs for displaying its full header text and full text content of all cells. If it requires more space than the table has, horizontal scrolling will be enabled. To prevent huge header text from polluting the table, a max-width of 700px is applied to each column. It can be overwritten by setting the respective column property. This mode adds a `minWidth` to each column. If the internally set `minWidth` is larger than the `width` set in the column options, it can lead to an unwanted scrollbar. To prevent this, you can override the internal `minWidth` by setting it yourself.
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/index.tsx:421]: I'm a bit confused by the `internal min width` part to be honest - what is the value of the internal minWidth? (and where is it in the code?)

File: packages/main/src/enums/AnalyticalTableScaleWidthMode.ts [hunk 2]
```diff
@@ -14,7 +14,11 @@ export enum AnalyticalTableScaleWidthMode {
    */
   Smart = 'Smart',
   /*
-   * Every column gets the space it needs for displaying its full header text and full text content of all cells. If it requires more space than the table has, horizontal scrolling will be enabled. To prevent huge header text from polluting the table, a max-width of 700px is applied to each column. It can be overwritten by setting the respective column property.
+   * Every column gets the space it needs for displaying its full header text and full text content of all cells. If it requires more space than the table has, horizontal scrolling will be enabled.
+   *
+   * __Note:__ To prevent huge header text from polluting the table, a max-width of 700px is applied to each column. It can be overwritten by setting the respective column property.
+   *
+   * __Note:__ This mode adds a `minWidth` to each column. If the internally set `minWidth` is larger than the `width` set in the column options, it can lead to an unwanted scrollbar. To prevent this, you can override the internal `minWidth` by setting it yourself.
```
Comment (MarcusNotheis) [inline packages/main/src/enums/AnalyticalTableScaleWidthMode.ts:21]: same as the comment above.

**Review by MarcusNotheis — APPROVED** [review]
