### PR TITLE
fix(AnalyticalTable): add "Filter" text to column popover

### LINKED ISSUE #6132: [Custom Filter]:[When we click ‘XX’ column header, we get the filter Header Popover List name is not provided.]
### Bug Description

When we click ‘XX’ column header, we get the custom filter Header Popover List in that list when you navigate using up down arrow key and when you focus on acceding and descending filter icon you get the proper meaningful but when your focus come to last  filter name is not provided.

For your better understanding I have attached some screenshots here:
image

I have also mentioned story book link where you can check this issue:
**Story Book Link:** https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--custom-filter

Steps:
1. Open Story Book Link and Speech Reader (JAWS)
2. After Opening Story Book Link you able to see table click on Age header you able to see Header Popover List
image

4. Navigate Header Popover List using arrow keys 
5. When your focus come to 
image
you can see no meaningful name provided.

### Affected Component

_No response_

### Expected Behaviour

Every UI should have meaningful name here for button name should be provided and same should be conveyed by the screen reader.

### Isolated Example

_No response_

### Steps to Reproduce

1.
2.
3.
...

### Log Output, Stack Trace or Screenshots

_No response_

### Priority

High

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

Windows

### Additional Context

_No response_

### Organization

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

### PR DESCRIPTION
**Pull request by Lukas742**
Fixes #6132

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx [hunk 1]
```diff
@@ -52,6 +54,16 @@ export const ColumnHeaderModal = (props: ColumnHeaderModalProperties) => {
...
+  const filterText = i18nBundle.getText(FILTER);
+
+  const filterStyles = useMemo(() => {
+    if (showFilter) {
+      return {
+        iconDimensions: `var(${getScopedVarName('--_ui5_list_item_icon_size')})`,
+        fontSize: `var(${getScopedVarName('--_ui5_list_item_title_size')})`
+      };
+    }
+  }, [showFilter]);
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.tsx:66]: why useMemo? The styles are passed inline as new objects

**Review by MarcusNotheis — CHANGES_REQUESTED** [review]

**Review by MarcusNotheis — APPROVED** [review]
