### PR TITLE
fix(AnalyticalTable): add a11y attribute for expanded state of row

### LINKED ISSUE #2773: Tree Table expansion not recited in Analytical Table row expansion(Accessibility Issue)
### **When I click on expansion for header of Tree Table option in Analytical Table the action is recited as expanded or collapsed but when I do the same for row expansion the action is not recited properly**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--tree-table
Analytical_Table_Tree_Table_Header_Expand_Reciting_Properly

https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--with-subcomponents
Analytical_Table_Tree_Table_Row_Expand_Not_Reciting_Properly

As you can clearly see the row expansion does not recite the collapse and expand properly.

### **Expected Behavior**
The expand and collapse should recite same text both in TreeTable header as well as in row

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Accessibility issue - Medium

### PR DESCRIPTION
**Pull request by Lukas742**
This PR adds the `aria-expanded` attribute to each row which is able to expand.

Fixes #2773

### CODE REVIEW

File: packages/main/src/components/AnalyticalTable/index.tsx [hunk 1]
```diff
@@ -33,6 +34,14 @@ import {
...
   useTable
 } from 'react-table';
+import {
+  COLLAPSE_NODE,
+  COLLAPSE_PRESS_SPACE,
+  EXPAND_NODE,
+  EXPAND_PRESS_SPACE,
+  SELECT_PRESS_SPACE,
+  UNSELECT_PRESS_SPACE
+} from '../../../dist/assets/i18n/i18n-defaults';
```
Comment (MarcusNotheis) [inline packages/main/src/components/AnalyticalTable/index.tsx:44]: should we rather use the `@ui5/webcomponents-react/dist/` import here?

**Review by MarcusNotheis — APPROVED** [review]
